name: Deploy to WordPress.org
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: New release

    runs-on: ubuntu-latest

    env:
      SLUG: "bundle-product-manager-for-woocommerce"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies with caching
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev --optimize-autoloader --classmap-authoritative"

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SLUG: ${{ env.SLUG }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
